//! The enum variants are used to represent the raw tokens in a more Rust-friendly way.

mod flags;
mod numeric_flags;
mod raw_token_impl;
mod tag_operations;

mod biome;
mod caste;
mod color_modification;
mod condition;
mod creature;
mod creature_effect;
mod creature_effect_property;
mod creature_variation;
mod creature_variation_rule;
mod entity;
mod environment_class;
mod fuel_type;
mod gait_modifier;
mod gait_type;
mod graphic_type;
mod growth;
mod inclusion_type;
mod inorganic;
mod material_property;
mod material_state;
mod material_type;
mod material_usage;
mod modification;
mod object_type;
mod plant;
mod plant_graphic_template;
mod plant_growth;
mod plant_growth_type;
mod plant_part;
mod position;
mod season;
mod select_creature_rule;
mod shrub;
mod syndrome;
mod tile_page;
mod tree;
mod twig_placement;

pub use biome::BiomeToken;
pub use caste::CasteToken;
pub use color_modification::ColorModificationToken;
pub use condition::ConditionToken;
pub use creature::CreatureToken;
pub use creature_effect::CreatureEffectToken;
pub use creature_effect_property::CreatureEffectPropertyToken;
pub use creature_variation::CreatureVariationToken;
pub use creature_variation_rule::CreatureVariationRuleToken;
pub use entity::EntityToken;
pub use environment_class::EnvironmentClassToken;
pub use fuel_type::FuelTypeToken;
pub use gait_modifier::GaitModifierToken;
pub use gait_type::GaitTypeToken;
pub use graphic_type::GraphicTypeToken;
pub use growth::GrowthToken;
pub use inclusion_type::InclusionTypeToken;
pub use inorganic::InorganicToken;
pub use material_property::MaterialPropertyToken;
pub use material_state::MaterialStateToken;
pub use material_type::MaterialTypeToken;
pub use material_usage::MaterialUsageToken;
pub use modification::ModificationToken;
pub use object_type::ObjectType;
pub use plant::PlantToken;
pub use plant_graphic_template::PlantGraphicTemplateToken;
pub use plant_growth::PlantGrowthToken;
pub use plant_growth_type::PlantGrowthTypeToken;
pub use plant_part::PlantPartToken;
pub use position::PositionToken;
pub use season::SeasonToken;
pub use select_creature_rule::SelectCreatureRuleToken;
pub use shrub::ShrubToken;
pub use syndrome::SyndromeToken;
pub use tile_page::TilePageToken;
pub use tree::TreeToken;
pub use twig_placement::TwigPlacementToken;
