//! String token to parsed tag map for condition tokens.

use crate::{
    custom_types::{Dimensions, PartSpecifier},
    tokens::ConditionToken,
};

/// Map of condition tags to their string representation.
pub static CONDITION_TOKENS: phf::Map<&'static str, ConditionToken> = phf::phf_map! {
  "DEFAULT" => ConditionToken::Default,
  "PORTRAIT" => ConditionToken::Portrait,
  "ANIMATED" => ConditionToken::Animated,
  "CORPSE" => ConditionToken::Corpse,
  "CHILD" => ConditionToken::ChildPrime,
  "TRAINED_WAR" => ConditionToken::TrainedWar,
  "TRAINED_HUNTER" => ConditionToken::TrainedHunter,
  "LIST_ICON" => ConditionToken::ListIcon,
  "SKELETON" => ConditionToken::Skeleton,
  "SKELETON_WITH_SKULL" => ConditionToken::SkeletonWithSkull,
  "ZOMBIE" => ConditionToken::Zombie,
  "NECROMANCER" => ConditionToken::Necromancer,
  "MALE" => ConditionToken::Male,
  "FEMALE" => ConditionToken::Female,
  "VAMPCURSE" => ConditionToken::VampireCursed,
  "GHOUL" => ConditionToken::Ghoul,
  "GHOST" => ConditionToken::Ghost,
  "DISTURBED_DEAD" => ConditionToken::DisturbedDead,
  "REMAINS" => ConditionToken::Remains,
  "VERMIN" => ConditionToken::Vermin,
  "LIGHT_VERMIN" => ConditionToken::LightVermin,
  "HIVE" => ConditionToken::Hive,
  "SWARM_SMALL" => ConditionToken::SwarmSmall,
  "SWARM_MEDIUM" => ConditionToken::SwarmMedium,
  "SWARM_LARGE" => ConditionToken::SwarmLarge,

  "NOT_ARTIFACT" => ConditionToken::NotArtifact,
  "IS_CRAFTED_ARTIFACT" => ConditionToken::CraftedArtifact,

  "SHRUB" => ConditionToken::Shrub,
  "PICKED" => ConditionToken::Picked,
  "SEED" => ConditionToken::Seed,
  "CROP" => ConditionToken::Crop,
  "CROP_SPROUT" => ConditionToken::CropSprout,
  "CROP_L" => ConditionToken::CropL,
  "CROP_M" => ConditionToken::CropM,
  "CROP_R" => ConditionToken::CropR,
  "SHRUB_DEAD" => ConditionToken::ShrubDead,
  "SAPLING" => ConditionToken::Sapling,

  "CONDITION_NOT_CHILD" => ConditionToken::NotChild,
  "CONDITION_CLASS" => ConditionToken::Class,
  "CONDITION_CHILD" => ConditionToken::Child,
  "CONDITION_BABY" => ConditionToken::Baby,
  "CONDITION_HAUL_COUNT_MIN" => ConditionToken::HaulCountMin { count: 0},
  "CONDITION_HAUL_COUNT_MAX" => ConditionToken::HaulCountMax { count: 0},
  "CONDITION_ITEM_WORN" => ConditionToken::ItemWorn {item_identifier: String::new(), selector: Vec::new(), specifier: PartSpecifier::Category},
  "CONDITION_PROFESSION_CATEGORY" => ConditionToken::ProfessionCategory,
  "CONDITION_SYN_CLASS" => ConditionToken::SyndromeClass {syndrome: String::new()},
  "CONDITION_CASTE" => ConditionToken::Caste,
  "CONDITION_TISSUE_LAYER" => ConditionToken::TissueLayer {selector: Vec::new(), specifier: PartSpecifier::Category},
  "CONDITION_MATERIAL_FLAG" => ConditionToken::MaterialFlag,
  "CONDITION_MATERIAL_TYPE" => ConditionToken::MaterialType,
  "CONDITION_DYE" => ConditionToken::Dye,
  "CONDITION_DYED" => ConditionToken::Dye,
  "CONDITION_NOT_DYED" => ConditionToken::NotDyed,
  "SHUT_OFF_IF_ITEM_PRESENT" => ConditionToken::ShutOffIfItemPresent,
  "CONDITION_RANDOM_PART_INDEX" => ConditionToken::RandomPartIndex {identifier: String::new(), index:0, range: 0},
  "CONDITION_GHOST" => ConditionToken::Ghost,
  "TISSUE_MAY_HAVE_COLOR" => ConditionToken::TissueMayHaveColor {colors: Vec::new(),},
  "TISSUE_MIN_LENGTH" => ConditionToken::TissueMinLength {length:0},
  "TISSUE_MAX_LENGTH" => ConditionToken::TissueMaxLength {length:0},
  "TISSUE_MAY_HAVE_SHAPING" => ConditionToken::TissueMayHaveShaping {shaping: String::new()},
  "TISSUE_NOT_SHAPED" => ConditionToken::TissueNotShaped,
  "TISSUE_SWAP" => ConditionToken::TissueSwap {condition: String::new(), tile_page_identifier: String::new(), tile_position: Dimensions::zero(), value: 0},
  "TISSUE_MIN_CURLY" => ConditionToken::TissueMinCurly,
  "TISSUE_MAX_CURLY" => ConditionToken::TissueMaxCurly,
  // Generic condition (or something)
  "CONDITION" => ConditionToken::Condition,

  // Professions...
  "HAMMERMAN" => ConditionToken::Hammerman,
  "MASTER_HAMMERMAN" => ConditionToken::MasterHammerman,
  "SPEARMAN" => ConditionToken::Spearman,
  "MASTER_SPEARMAN" => ConditionToken::MasterSpearman,
  "WRESTLER" => ConditionToken::Wrestler,
  "MASTER_WRESTLER" => ConditionToken::MasterWrestler,
  "AXEMAN" => ConditionToken::Axeman,
  "MASTER_AXEMAN" => ConditionToken::MasterAxeman,
  "SWORDSMAN" => ConditionToken::Swordsman,
  "MASTER_SWORDSMAN" => ConditionToken::MasterSwordsman,
  "MACEMAN" => ConditionToken::Maceman,
  "MASTER_MACEMAN" => ConditionToken::MasterMaceman,
  "PIKEMAN" => ConditionToken::Pikeman,
  "MASTER_PIKEMAN" => ConditionToken::MasterPikeman,
  "RECRUIT" => ConditionToken::Recruit,
  "THIEF" => ConditionToken::Thief,
  "MASTER_THIEF" => ConditionToken::MasterThief,
  "LASHER" => ConditionToken::Lasher,
  "MASTER_LASHER" => ConditionToken::MasterLasher,
  "MONSTER_SLAYER" => ConditionToken::MonsterSlayer,
  "CROSSBOWMAN" => ConditionToken::Crossbowman,
  "MASTER_CROSSBOWMAN" => ConditionToken::MasterCrossbowman,
  "BOWMAN" => ConditionToken::Bowman,
  "MASTER_BOWMAN" => ConditionToken::MasterBowman,
  "BLOWGUNMAN" => ConditionToken::Blowgunman,
  "MASTER_BLOWGUNMAN" => ConditionToken::MasterBlowgunman,
  "BEAST_HUNTER" => ConditionToken::BeastHunter,
  "SCOUT" => ConditionToken::Scout,
  "RANGER" => ConditionToken::Ranger,
  "HUNTER" => ConditionToken::Hunter,
  "SAGE" => ConditionToken::Sage,
  "SCHOLAR" => ConditionToken::Scholar,
  "PHILOSOPHER" => ConditionToken::Philosopher,
  "MATHEMATICIAN" => ConditionToken::Mathematician,
  "HISTORIAN" => ConditionToken::Historian,
  "ASTRONOMER" => ConditionToken::Astronomer,
  "NATURALIST" => ConditionToken::Naturalist,
  "CHEMIST" => ConditionToken::Chemist,
  "GEOGRAPHER" => ConditionToken::Geographer,
  "SCRIBE" => ConditionToken::Scribe,
  "BOOKBINDER" => ConditionToken::Bookbinder,
  "PERFORMER" => ConditionToken::Performer,
  "POET" => ConditionToken::Poet,
  "BARD" => ConditionToken::Bard,
  "DANCER" => ConditionToken::Dancer,

  "LS_PALETTE" => ConditionToken::LayerSetPalette {name: String::new()},
  "LS_PALETTE_FILE" => ConditionToken::LayerSetPaletteFile {path: String::new()},
  "LS_PALETTE_DEFAULT" => ConditionToken::LayerSetPaletteDefault {default_row: 0},
  "VERMIN_ALT" => ConditionToken::VerminAlt,
  "LIGHT_VERMIN_ALT" => ConditionToken::LightVerminAlt,
  "LIGHT_SWARM_SMALL" => ConditionToken::LightSwarmSmall,
  "LIGHT_SWARM_MEDIUM" => ConditionToken::LightSwarmMedium,
  "LIGHT_SWARM_LARGE" => ConditionToken::LightSwarmLarge,
  "ITEM_QUALITY" => ConditionToken::ItemQuality {quality: 0},
  "USE_PALETTE" => ConditionToken::UsePalette,
  "USE_STANDARD_PALETTE_FROM_ITEM" => ConditionToken::UseStandardPaletteFromItem,
  "BP_APPEARANCE_MODIFIER_RANGE" => ConditionToken::BodyPartAppearanceModifierRange,
  "CONDITION_BP" => ConditionToken::BodyPart {selector: Vec::new(), specifier: PartSpecifier::Category},
  "LG_CONDITION_BP" => ConditionToken::LayerGroupBodyPart {selector: Vec::new(), specifier: PartSpecifier::Category},
  "TISSUE_MIN_DENSITY" => ConditionToken::TissueMinDensity {density: 0},
  "TISSUE_MAX_DENSITY" => ConditionToken::TissueMaxDensity {density: 0},
  "CONDITION_BODY_SIZE_MIN" => ConditionToken::BodySizeMin {size: 0},
  "CONDITION_BODY_SIZE_MAX" => ConditionToken::BodySizeMax {size: 0},
  "GLOW" => ConditionToken::Glow,
  "GLOW_CHILD" => ConditionToken::GlowChild,
  "GLOW_LEFT_GONE" => ConditionToken::GlowLeftGone,
  "GLOW_RIGHT_GONE" => ConditionToken::GlowRightGone,
  "LAW_ENFORCE" => ConditionToken::LawEnforcement,
  "TAX_ESCORT" => ConditionToken::TaxEscort,
  "ADVENTURER" => ConditionToken::Adventurer,
  "EGG" => ConditionToken::Egg,
  "CDI_LIST_ICON" => ConditionToken::CdiListIcon,
  "BABY" => ConditionToken::BabyPrime,
};
