//! String token to parsed tag map for creature tokens.

use crate::{
    custom_types::{Color, Name, TileCharacter},
    tokens::CreatureToken,
};

/// A map of creature tags to their respective enum values.
pub static CREATURE_TOKENS: phf::Map<&'static str, CreatureToken> = phf::phf_map! {
    "ARTIFICIAL_HIVEABLE" => CreatureToken::ArtificialHiveable,
    "DOES_NOT_EXIST" => CreatureToken::DoesNotExist,
    "EVIL" => CreatureToken::Evil,
    "GOOD" => CreatureToken::Good,
    "FANCIFUL" => CreatureToken::Fanciful,
    "SAVAGE" => CreatureToken::Savage,
    "GENERATED" => CreatureToken::Generated,
    "UBIQUITOUS" => CreatureToken::Ubiquitous,
    "VERMIN_FISH" => CreatureToken::VerminFish,
    "VERMIN_SOIL" => CreatureToken::VerminSoil,
    "VERMIN_SOIL_COLONY" => CreatureToken::VerminSoilColony,
    "VERMIN_ROTTER" => CreatureToken::VerminRotter,
    "VERMIN_GROUNDER" => CreatureToken::VerminGrounder,
    "VERMIN_EATER" => CreatureToken::VerminEater,
    "FREQUENCY" => CreatureToken::Frequency { frequency: 50 },
    "UNDERGROUND_DEPTH" => CreatureToken::UndergroundDepth { min: 0, max: 0 },
    "LARGE_ROAMING" => CreatureToken::LargeRoaming,
    "LOCAL_POPS_CONTROLLABLE" => CreatureToken::LocalPopsControllable,
    "LOCAL_POPS_PRODUCE_HEROES" => CreatureToken::LocalPopsProduceHeroes,
    "LOOSE_CLUSTERS" => CreatureToken::LooseClusters,
    "MUNDANE" => CreatureToken::Mundane,
    "BIOME" => CreatureToken::Biome { id: String::new() },
    "PREFSTRING" => CreatureToken::PrefString { pref_string: String::new() },
    "NAME" => CreatureToken::Name { name: Name::new_empty() },
    "GENERAL_BABY_NAME" => CreatureToken::GeneralBabyName { name: Name::new_empty() },
    "GENERAL_CHILD_NAME" => CreatureToken::GeneralChildName { name: Name::new_empty() },
    "POPULATION_NUMBER" => CreatureToken::PopulationNumber { min: 1, max: 1 },
    "COPY_TAGS_FROM" => CreatureToken::CopyTagsFrom { creature: String::new() },
    "CREATURE_TILE" => CreatureToken::CreatureTile { character: TileCharacter::new() },
    "ALTTILE" => CreatureToken::AltTile { character: TileCharacter::new() },
    "COLOR" => CreatureToken::Color { color: Color::new() },
    "GLOWCOLOR" => CreatureToken::GlowColor { color: Color::new() },
    "GLOWTILE" => CreatureToken::GlowTile { character: TileCharacter::new()  },
    "CHANGE_FREQUENCY_PERC" => CreatureToken::ChangeFrequencyPercent { percent: 0 },
    "CLUSTER_NUMBER" => CreatureToken::ClusterNumber { min: 1, max: 1 },
    "MATES_TO_BREED" => CreatureToken::MatesToBreed,
    "ALL_CASTES_ALIVE" => CreatureToken::AllCastesAlive,
    "TWO_GENDERS" => CreatureToken::TwoGenders,
    "SMALL_RACE" => CreatureToken::SmallRace,
    "OCCURS_AS_ENTITY_RACE" => CreatureToken::OccursAsEntityRace,
    "EQUIPMENT" => CreatureToken::Equipment,
    "EQUIPMENT_WAGON" => CreatureToken::EquipmentWagon,
};
