//! String token to parsed tag map for tree tokens.

use crate::tokens::TreeToken;

/// The mapping of tree tokens to their string representation
pub static TREE_TOKENS: phf::Map<&'static str, TreeToken> = phf::phf_map! {
  "TREE" => TreeToken::Tree,
  "TRUNK_NAME" => TreeToken::TrunkName,
  "MAX_TRUNK_HEIGHT" => TreeToken::MaxTrunkHeight,
  "MAX_TRUNK_DIAMETER" => TreeToken::MaxTrunkDiameter,
  "TRUNK_PERIOD" => TreeToken::TrunkPeriod,
  "TRUNK_WIDTH_PERIOD" => TreeToken::TrunkWidthPeriod,
  "BRANCH_NAME" => TreeToken::BranchName,
  "LIGHT_BRANCHES_NAME" => TreeToken::BranchName,
  "BRANCH_DENSITY" => TreeToken::BranchDensity,
  "LIGHT_BRANCH_DENSITY" => TreeToken::BranchDensity,
  "BRANCH_RADIUS" => TreeToken::BranchRadius,
  "LIGHT_BRANCH_RADIUS" => TreeToken::BranchRadius,
  "HEAVY_BRANCHES_NAME" => TreeToken::HeavyBranchesName,
  "DIRECTED_BRANCH_NAME" => TreeToken::HeavyBranchesName,
  "HEAVY_BRANCH_DENSITY" => TreeToken::HeavyBranchDensity,
  "DIRECTED_BRANCH_DENSITY" => TreeToken::HeavyBranchDensity,
  "HEAVY_BRANCH_RADIUS" => TreeToken::HeavyBranchRadius,
  "DIRECTED_BRANCH_RADIUS" => TreeToken::HeavyBranchRadius,
  "TRUNK_BRANCHING" => TreeToken::TrunkBranching,
  "ROOT_NAME" => TreeToken::RootName,
  "ROOTS_NAME" => TreeToken::RootName,
  "ROOT_DENSITY" => TreeToken::RootDensity,
  "TWIGS_NAME" => TreeToken::TwigsName,
  "TWIGS_SIDE_BRANCHES" => TreeToken::TwigsSideBranches,
  "TWIGS_ABOVE_BRANCHES" => TreeToken::TwigsAboveBranches,
  "TWIGS_BELOW_BRANCHES" => TreeToken::TwigsBelowBranches,
  "TWIGS_SIDE_HEAVY_BRANCHES" => TreeToken::TwigsSideHeavyBranches,
  "TWIGS_ABOVE_HEAVY_BRANCHES" => TreeToken::TwigsAboveHeavyBranches,
  "TWIGS_BELOW_HEAVY_BRANCHES" => TreeToken::TwigsBelowHeavyBranches,
  "TWIGS_SIDE_TRUNK" => TreeToken::TwigsSideTrunk,
  "TWIGS_ABOVE_TRUNK" => TreeToken::TwigsAboveTrunk,
  "TWIGS_BELOW_TRUNK" => TreeToken::TwigsBelowTrunk,
  "CAP_NAME" => TreeToken::CapName,
  "CAP_PERIOD" => TreeToken::CapPeriod,
  "CAP_RADIUS" => TreeToken::CapRadius,
  "TREE_TILE" => TreeToken::TreeTile,
  "DEAD_TREE_TILE" => TreeToken::DeadTreeTile,
  "SAPLING_TILE" => TreeToken::SaplingTile,
  "DEAD_SAPLING_TILE" => TreeToken::DeadSaplingTile,
  "TREE_COLOR" => TreeToken::TreeColor,
  "DEAD_TREE_COLOR" => TreeToken::DeadTreeColor,
  "SAPLING_COLOR" => TreeToken::SaplingColor,
  "DEAD_SAPLING_COLOR" => TreeToken::DeadSaplingColor,
  "SAPLING_DROWN_LEVEL" => TreeToken::SaplingDrownLevel,
  "TREE_DROWN_LEVEL" => TreeToken::TreeDrownLevel,
  "TREE_HAS_MUSHROOM_CAP" => TreeToken::TreeHasMushroomCap,
  "STANDARD_TILE_NAMES" => TreeToken::StandardTileNames,
  "SAPLING" => TreeToken::Sapling,
};
