use std::path::Path;

use specta::TypeCollection;
use specta_typescript::{ExportError, Typescript};

/// Generate typescript type defintions for all objects in `dfraw_parser` that might be used when working
/// with JSON objects serialized with serde.
///
/// # Errors
///
/// Will error if the Type bindings export fails
pub fn generate_bindings(output_path: &Path) -> Result<(), ExportError> {
    let exporter = Typescript::default().bigint(specta_typescript::BigIntExportBehavior::String);
    let mut types = TypeCollection::default();

    types
        .register::<dfraw_parser::tags::BiomeTag>()
        .register::<dfraw_parser::tags::CasteTag>()
        .register::<dfraw_parser::tags::ColorModificationTag>()
        .register::<dfraw_parser::tags::ConditionTag>()
        .register::<dfraw_parser::tags::CreatureTag>()
        .register::<dfraw_parser::tags::CreatureEffectTag>()
        .register::<dfraw_parser::tags::CreatureEffectPropertyTag>()
        .register::<dfraw_parser::tags::CreatureVariationTag>()
        .register::<dfraw_parser::tags::CreatureVariationRuleTag>()
        .register::<dfraw_parser::tags::EntityTag>()
        .register::<dfraw_parser::tags::EnvironmentClassTag>()
        .register::<dfraw_parser::tags::FuelTypeTag>()
        .register::<dfraw_parser::tags::GaitModifierTag>()
        .register::<dfraw_parser::tags::GaitTypeTag>()
        .register::<dfraw_parser::tags::GraphicTypeTag>()
        .register::<dfraw_parser::tags::GrowthTag>()
        .register::<dfraw_parser::tags::InclusionTypeTag>()
        .register::<dfraw_parser::tags::InorganicTag>()
        .register::<dfraw_parser::tags::MaterialPropertyTag>()
        .register::<dfraw_parser::tags::MaterialStateTag>()
        .register::<dfraw_parser::tags::MaterialTypeTag>()
        .register::<dfraw_parser::tags::MaterialUsageTag>()
        .register::<dfraw_parser::tags::ModificationTag>()
        .register::<dfraw_parser::tags::ObjectType>()
        .register::<dfraw_parser::tags::PlantTag>()
        .register::<dfraw_parser::tags::PlantGraphicTemplateTag>()
        .register::<dfraw_parser::tags::PlantGrowthTag>()
        .register::<dfraw_parser::tags::PlantGrowthTypeTag>()
        .register::<dfraw_parser::tags::PlantPartTag>()
        .register::<dfraw_parser::tags::PositionTag>()
        .register::<dfraw_parser::tags::SeasonTag>()
        .register::<dfraw_parser::tags::SelectCreatureRuleTag>()
        .register::<dfraw_parser::tags::ShrubTag>()
        .register::<dfraw_parser::tags::SyndromeTag>()
        .register::<dfraw_parser::tags::TilePageTag>()
        .register::<dfraw_parser::tags::TreeTag>()
        .register::<dfraw_parser::tags::TwigPlacementTag>()
        .register::<dfraw_parser::BodySize>()
        .register::<dfraw_parser::Caste>()
        .register::<dfraw_parser::Color>()
        .register::<dfraw_parser::Creature>()
        .register::<dfraw_parser::CreatureEffect>()
        .register::<dfraw_parser::CreatureVariation>()
        .register::<dfraw_parser::CustomGraphicExtension>()
        .register::<dfraw_parser::Dimensions>()
        .register::<dfraw_parser::Entity>()
        .register::<dfraw_parser::Gait>()
        .register::<dfraw_parser::Graphic>()
        .register::<dfraw_parser::ModuleInfo>()
        .register::<dfraw_parser::Inorganic>()
        .register::<dfraw_parser::Material>()
        .register::<dfraw_parser::MaterialMechanics>()
        .register::<dfraw_parser::MaterialTemplate>()
        .register::<dfraw_parser::MechanicalProperties>()
        .register::<dfraw_parser::Milkable>()
        .register::<dfraw_parser::Name>()
        .register::<dfraw_parser::Plant>()
        .register::<dfraw_parser::PlantGrowth>()
        .register::<dfraw_parser::Position>()
        .register::<dfraw_parser::SeedMaterial>()
        .register::<dfraw_parser::SelectCreature>()
        .register::<dfraw_parser::Shrub>()
        .register::<dfraw_parser::SpriteGraphic>()
        .register::<dfraw_parser::SpriteLayer>()
        .register::<dfraw_parser::StateNames>()
        .register::<dfraw_parser::SteamData>()
        .register::<dfraw_parser::Syndrome>()
        .register::<dfraw_parser::Temperatures>()
        .register::<dfraw_parser::Tile>()
        .register::<dfraw_parser::TilePage>()
        .register::<dfraw_parser::Tree>()
        .register::<dfraw_parser::metadata::ParserOptions>()
        .register::<dfraw_parser::metadata::RawModuleLocation>()
        .register::<dfraw_parser::metadata::RawMetadata>()
        .register::<dfraw_parser::metadata::TagComplexity>()
        .register::<dfraw_parser::metadata::RawObject>()
        .register::<dfraw_parser_sqlite_lib::TilePageData>()
        .register::<dfraw_parser_sqlite_lib::SpriteGraphicData>()
        .register::<dfraw_parser_sqlite_lib::ClientOptions>()
        .register::<dfraw_parser_sqlite_lib::SearchQuery>()
        .register::<dfraw_parser_sqlite_lib::ResultWithId>()
        .register::<dfraw_parser_sqlite_lib::SearchResults>();

    exporter.export_to(output_path, &types)
}
