use std::path::Path;

use specta::TypeCollection;
use specta_typescript::{ExportError, Typescript};

/// Generate typescript type defintions for all objects in `dfraw_parser` that might be used when working
/// with JSON objects serialized with serde.
///
/// # Errors
///
/// Will error if the Type bindings export fails
pub fn generate_bindings(output_path: &Path) -> Result<(), ExportError> {
    let exporter = Typescript::default().bigint(specta_typescript::BigIntExportBehavior::String);
    let mut types = TypeCollection::default();

    types
        .register::<dfraw_parser::tokens::BiomeToken>()
        .register::<dfraw_parser::tokens::CasteToken>()
        .register::<dfraw_parser::tokens::ColorModificationToken>()
        .register::<dfraw_parser::tokens::ConditionToken>()
        .register::<dfraw_parser::tokens::CreatureToken>()
        .register::<dfraw_parser::tokens::CreatureEffectToken>()
        .register::<dfraw_parser::tokens::CreatureEffectPropertyToken>()
        .register::<dfraw_parser::tokens::CreatureVariationToken>()
        .register::<dfraw_parser::tokens::CreatureVariationRuleToken>()
        .register::<dfraw_parser::tokens::EntityToken>()
        .register::<dfraw_parser::tokens::EnvironmentClassToken>()
        .register::<dfraw_parser::tokens::FuelTypeToken>()
        .register::<dfraw_parser::tokens::GaitModifierToken>()
        .register::<dfraw_parser::tokens::GaitTypeToken>()
        .register::<dfraw_parser::tokens::GraphicTypeToken>()
        .register::<dfraw_parser::tokens::GrowthToken>()
        .register::<dfraw_parser::tokens::InclusionTypeToken>()
        .register::<dfraw_parser::tokens::InorganicToken>()
        .register::<dfraw_parser::tokens::MaterialPropertyToken>()
        .register::<dfraw_parser::tokens::MaterialStateToken>()
        .register::<dfraw_parser::tokens::MaterialTypeToken>()
        .register::<dfraw_parser::tokens::MaterialUsageToken>()
        .register::<dfraw_parser::tokens::ModificationToken>()
        .register::<dfraw_parser::tokens::ObjectType>()
        .register::<dfraw_parser::tokens::PlantToken>()
        .register::<dfraw_parser::tokens::PlantGraphicTemplateToken>()
        .register::<dfraw_parser::tokens::PlantGrowthToken>()
        .register::<dfraw_parser::tokens::PlantGrowthTypeToken>()
        .register::<dfraw_parser::tokens::PlantPartToken>()
        .register::<dfraw_parser::tokens::PositionToken>()
        .register::<dfraw_parser::tokens::SeasonToken>()
        .register::<dfraw_parser::tokens::SelectCreatureRuleToken>()
        .register::<dfraw_parser::tokens::ShrubToken>()
        .register::<dfraw_parser::tokens::SyndromeToken>()
        .register::<dfraw_parser::tokens::TilePageToken>()
        .register::<dfraw_parser::tokens::TreeToken>()
        .register::<dfraw_parser::tokens::TwigPlacementToken>()
        .register::<dfraw_parser::BodySize>()
        .register::<dfraw_parser::Caste>()
        .register::<dfraw_parser::Color>()
        .register::<dfraw_parser::Creature>()
        .register::<dfraw_parser::CreatureEffect>()
        .register::<dfraw_parser::CreatureVariation>()
        .register::<dfraw_parser::CustomGraphicExtension>()
        .register::<dfraw_parser::Dimensions>()
        .register::<dfraw_parser::Entity>()
        .register::<dfraw_parser::Gait>()
        .register::<dfraw_parser::Graphic>()
        .register::<dfraw_parser::ModuleInfo>()
        .register::<dfraw_parser::Inorganic>()
        .register::<dfraw_parser::Material>()
        .register::<dfraw_parser::MaterialMechanics>()
        .register::<dfraw_parser::MaterialTemplate>()
        .register::<dfraw_parser::MechanicalProperties>()
        .register::<dfraw_parser::Milkable>()
        .register::<dfraw_parser::Name>()
        .register::<dfraw_parser::Plant>()
        .register::<dfraw_parser::PlantGrowth>()
        .register::<dfraw_parser::Position>()
        .register::<dfraw_parser::SeedMaterial>()
        .register::<dfraw_parser::SelectCreature>()
        .register::<dfraw_parser::Shrub>()
        .register::<dfraw_parser::SpriteGraphic>()
        .register::<dfraw_parser::SpriteLayer>()
        .register::<dfraw_parser::StateNames>()
        .register::<dfraw_parser::SteamData>()
        .register::<dfraw_parser::Syndrome>()
        .register::<dfraw_parser::Temperatures>()
        .register::<dfraw_parser::Tile>()
        .register::<dfraw_parser::TilePage>()
        .register::<dfraw_parser::Tree>()
        .register::<dfraw_parser::metadata::ParserOptions>()
        .register::<dfraw_parser::metadata::RawModuleLocation>()
        .register::<dfraw_parser::metadata::RawMetadata>()
        .register::<dfraw_parser::metadata::TagComplexity>()
        .register::<dfraw_parser::metadata::RawObject>()
        .register::<dfraw_parser_sqlite_lib::models::TilePageData>()
        .register::<dfraw_parser_sqlite_lib::models::SpriteGraphicData>()
        .register::<dfraw_parser_sqlite_lib::ClientOptions>()
        .register::<dfraw_parser_sqlite_lib::SearchQuery>()
        .register::<dfraw_parser_sqlite_lib::NumericFilter>()
        .register::<dfraw_parser_sqlite_lib::NumericConstraint>()
        .register::<dfraw_parser_sqlite_lib::ResultWithId>()
        .register::<dfraw_parser_sqlite_lib::SearchResults>();

    exporter.export_to(output_path, &types)
}
