//! The enum variants are used to represent the raw tokens in a more Rust-friendly way.

mod biome;
mod caste;
mod color_modification;
mod condition;
mod creature;
mod creature_effect;
mod creature_effect_property;
mod creature_variation;
mod creature_variation_rule;
mod entity;
mod environment_class;
mod fuel_type;
mod gait_modifier;
mod gait_type;
mod graphic_type;
mod growth;
mod inclusion_type;
mod inorganic;
mod material_property;
mod material_state;
mod material_type;
mod material_usage;
mod modification;
mod object_type;
mod plant;
mod plant_graphic_template;
mod plant_growth;
mod plant_growth_type;
mod plant_part;
mod position;
mod season;
mod select_creature_rule;
mod shrub;
mod syndrome;
mod tile_page;
mod tree;
mod twig_placement;

pub use biome::BiomeTag;
pub use caste::CasteTag;
pub use color_modification::ColorModificationTag;
pub use condition::ConditionTag;
pub use creature::CreatureTag;
pub use creature_effect::CreatureEffectTag;
pub use creature_effect_property::CreatureEffectPropertyTag;
pub use creature_variation::CreatureVariationTag;
pub use creature_variation_rule::CreatureVariationRuleTag;
pub use entity::EntityTag;
pub use environment_class::EnvironmentClassTag;
pub use fuel_type::FuelTypeTag;
pub use gait_modifier::GaitModifierTag;
pub use gait_type::GaitTypeTag;
pub use graphic_type::GraphicTypeTag;
pub use growth::GrowthTag;
pub use inclusion_type::InclusionTypeTag;
pub use inorganic::InorganicTag;
pub use material_property::MaterialPropertyTag;
pub use material_state::MaterialStateTag;
pub use material_type::MaterialTypeTag;
pub use material_usage::MaterialUsageTag;
pub use modification::ModificationTag;
pub use object_type::ObjectType;
pub use plant::PlantTag;
pub use plant_graphic_template::PlantGraphicTemplateTag;
pub use plant_growth::PlantGrowthTag;
pub use plant_growth_type::PlantGrowthTypeTag;
pub use plant_part::PlantPartTag;
pub use position::PositionTag;
pub use season::SeasonTag;
pub use select_creature_rule::SelectCreatureRuleTag;
pub use shrub::ShrubTag;
pub use syndrome::SyndromeTag;
pub use tile_page::TilePageTag;
pub use tree::TreeTag;
pub use twig_placement::TwigPlacementTag;
