CREATE TABLE condition
(
    id          INTEGER PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT
);

INSERT INTO condition (name, description)
VALUES ('None', 'No condition'),
       ('Animated', 'Condition of being animated'),
       ('Corpse', 'Condition of being a corpse'),
       ('Child', 'Condition of being a child'),
       ('Baby', 'Condition of being a baby'),
       ('TrainedHunter', 'Condition of being trained for hunting'),
       ('TrainedWar', 'Condition of being trained for war'),
       ('ListIcon', 'Condition of being a list icont'),
       ('Skeleton', 'Condition of being a skeleton'),
       ('SkeletonWithSkull', 'Condition of being a skeleton with a skull'),
       ('Zombie', 'Condition of being a zombie'),
       ('Necromancer', 'Condition of being a necromancer'),
       ('Male', 'Condition of being male'),
       ('Female', 'Condition of being female'),
       ('VampireCursed', 'Condition of being a vampire'),
       ('Ghoul', 'Condition of being a ghoul'),
       ('DisturbedDead', 'Condition of being a disturbed dead'),
       ('Remains', 'Condition of being remains'),
       ('Vermin', 'Condition of being a vermin'),
       ('LightVermin', 'Condition of being a light vermin'),
       ('Hive', 'Condition of being a hive'),
       ('SwarmSmall', 'Condition of being a small swarm'),
       ('SwarmMedium', 'Condition of being a medium swarm'),
       ('SwarmLarge', 'Condition of being a large swarm'),
       ('NotArtifact', 'Condition of being not an artifact'),
       ('CraftedArtifact', 'Condition of being a crafted artifact'),
       ('Dye', 'Condition of being dyed'),
       ('NotDyed', 'Condition of not being dyed'),
       ('Crop', 'Condition of being a crop'),
       ('Seed', 'Condition of being a seed'),
       ('Picked', 'Condition of being a plant (picked)'),
       ('Shrub', 'Condition of being a shrub'),
       ('Sapling', 'Condition of being a sapling'),
       ('CropSprout', 'Condition of being a crop sprout'),
       ('CropL', 'Condition of being a large crop'),
       ('CropM', 'Condition of being a medium crop'),
       ('CropR', 'Condition of being a small crop'),
       ('ShrubDead', 'Condition of being a dead shrub'),
       ('NotChild', 'Condition of not being a child'),
       ('HaulCountMin', 'Condition of being at least so many hauled'),
       ('HaulCountMax', 'Condition of being at most so many hauled'),
       ('ItemWorn', 'Condition of being a worn item'),
       ('ProfessionCategory', 'Condition of having a profession'),
       ('Class', 'Condition of being a class'),
       ('SyndromeClass', 'Condition of being a syndrome class'),
       ('Caste', 'Condition of being a caste'),
       ('TissueLayer', 'Condition of being a tissue layer'),
       ('MaterialFlag', 'Condition of being a material flag'),
       ('MaterialType', 'Condition of being a material type'),
       ('ShutOffIfItemPresent', 'Condition of being off if an item is present'),
       ('RandomPartIndex', 'Condition of being a random part index'),
       ('Ghost', 'Condition of being a ghost'),
       ('TissueMayHaveColor', 'Condition of being a tissue that may have color'),
       ('TissueMinLength', 'Condition of being a tissue that is at least so long'),
       ('TissueMaxLength', 'Condition of being a tissue that is at most so long'),
       ('TissueMinCurly', 'Condition of being a tissue at least so curly'),
       ('TissueMaxCurly', 'Condition of being a tissue at most so curly'),
       ('TissueMayHaveShaping', 'Condition of being a tissue that may have a shape'),
       ('TissueNotShaped', 'Condition of being a tissue that is not shaped'),
       ('TissueSwap', 'Condition of being a swapped tissue'),
       ('Layer', 'Condition of being a specific layer (start layer definition)'),
       ('LayerSet', 'Condition of being a specific layer set of layers'),
       ('LayerGroup', 'Condition of being a specific layer group'),
       ('EndLayerGroup', 'Condition of being a specific layer group set of layers'),
       ('BodyUpper', 'Condition of being the upper body'),
       ('CopyOfTemplate', 'Condition of being a copy of a template'),
       ('Hammerman', 'Hammerman profession'),
       ('MasterHammerman', 'Master Hammerman profession'),
       ('Spearman', 'Spearman profession'),
       ('MasterSpearman', 'Master Spearman profession'),
       ('Wrestler', 'Wrestler profession'),
       ('MasterWrestler', 'Master Wrestler profession'),
       ('Axeman', 'Axeman profession'),
       ('MasterAxeman', 'Master Axeman profession'),
       ('Swordsman', 'Swordsman profession'),
       ('MasterSwordsman', 'Master Swordsman profession'),
       ('Maceman', 'Maceman profession'),
       ('MasterMaceman', 'Master Maceman profession'),
       ('Pikeman', 'Pikeman profession'),
       ('MasterPikeman', 'Master Pikeman profession'),
       ('Recruit', 'Recruit profession'),
       ('Thief', 'Thief profession'),
       ('MasterThief', 'Master Thief profession'),
       ('Lasher', 'Lasher profession'),
       ('MasterLasher', 'Master Lasher profession'),
       ('MonsterSlayer', 'Monster slayer profession'),
       ('Crossbowman', 'Crossbowman profession'),
       ('MasterCrossbowman', 'Master Crossbowman profession'),
       ('Bowman', 'Bowman profession'),
       ('MasterBowman', 'Master Bowman profession'),
       ('Blowgunman', 'Blowgunman profession'),
       ('MasterBlowgunman', 'Master Blowgunman profession'),
       ('BeastHunter', 'Beat hunter profession'),
       ('Scout', 'Scout profession'),
       ('Ranger', 'Ranger profession'),
       ('Hunter', 'Hunter profession'),
       ('Sage', 'Sage profession'),
       ('Scholar', 'Scholar profession'),
       ('Philosopher', 'Philosopher profession'),
       ('Mathematician', 'Mathematician profession'),
       ('Historian', 'Historian profession'),
       ('Astronomer', 'Astronomer profession'),
       ('Naturalist', 'Naturalist profession'),
       ('Chemist', 'Chemist profession'),
       ('Geographer', 'Geographer profession'),
       ('Scribe', 'Scribe profession'),
       ('Bookbinder', 'Bookbinder profession'),
       ('Performer', 'Performer profession'),
       ('Poet', 'Poet profession'),
       ('Bard', 'Bard profession'),
       ('Dancer', 'Dancer profession');