// Type of object
Table object_type {
  id int [pk, increment]
  identifier text [note: 'How its defined in the raw file, e.g. CREATURE or ITEM_AMMO']
  description text [note: 'Human-readable, English description, e.g. Creature or Ammo Item']
}

Table biome {
  id int [pk, increment]
  identifier text
  description text
}

// Author
Table author {
  id int [pk, increment]
  name text
}

// Location table meant for the "official" locations
// Vanilla, downloaded mods, installed mods
Table location {
  id int [pk, increment]
  identifier text
  path text
  relative_path text
}

// Module info, mostly from info.txt
// This is for the entire "module" or folder of raws
Table module {
  id int [pk, increment]
  identifier text
  name text
  description text
  version text
  numerical_version int
  earliest_compat_version text
  earliest_compat_numerical_version int
  steam_data int [ref: > steam_data.id]
}

// Answers the "requires module" field
Table module_required_module {
  module_id int [ref: > module.id]
  required_module_id int [ref: > module.id]

  indexes {
    (module_id, required_module_id) [pk]
  }
}

// Answers the "conflicts with module" field
Table module_conflicts_with_module {
  module_id int [ref: > module.id]
  conflicting_module_id int [ref: > module.id]

  indexes {
    (module_id, conflicting_module_id) [pk]
  }
}

// Answers the "required before" field
Table module_required_before_module {
  module_id int [ref: > module.id]
  required_before_module_id int [ref: > module.id]

  indexes {
    (module_id, required_before_module_id) [pk]
  }
}

// Answers the "required after" field
Table module_required_after_module {
  module_id int [ref: > module.id]
  required_after_module_id int [ref: > module.id]

  indexes {
    (module_id, required_after_module_id) [pk]
  }
}


// Metadata for a single raw file
Table raw_metadata {
  id int [pk, increment]
  identifier text
  module int [ref: > module.id ]
  module_location int [ref: > location.id]
  object_type int [ref: > object_type.id]
  raw_file_path text
}

// Steam data, optional and any field can be filled
Table steam_data {
  id int [pk, increment]
  file_id text // This is a u64
  title text
  description text
  changelog text
}

Table steam_tag {
  id int [pk, increment]
  name text
  has_value bit
}

Table steam_data_2_tag {
  steam_data_id int [ref: > steam_data.id]
  steam_tag_id int [ref: > steam_tag.id]

  indexes {
    (steam_data_id, steam_tag_id) [pk]
  }
}

Table steam_data_2_value_tag {
  steam_data_id int [ref: > steam_data.id]
  steam_tag_id int [ref: > steam_tag.id]
  value text
  indexes {
    (steam_data_id, steam_tag_id) [pk]
  }
}

// Raw Data Descriptions
Table creature {
  id int [increment]
  metadata int [ref: > raw_metadata.id]
  identifier text
  tile int [ref: > tile.id]
  frequency int
  cluster_number int [ref: > min_max_data.id]
  population_number int [ref: > min_max_data.id]
  underground_depth int [ref: > min_max_data.id]
  general_baby_name int [ref: > name_data.id]
  name int [ref: > name_data.id]
  copy_tags_from_identifier text [note: 'The identifier of the creature to copy']

  indexes {
    id [pk]
    (id, identifier)
    identifier
  }
}

Table apply_creature_variation_step {
  creature_id int [ref: > creature.id]
  raw_step_text text
}

Table select_creature_variation_step {
  creature_id int [ref: > creature.id]
  raw_step_text text
}

Table creature_pref_strings {
  creature_id int [ref: > creature.id]
  pref_string text

  indexes {
    (creature_id, pref_string) [pk]
  }
}

Table creature_2_biome {
  creature_id int [ref: > creature.id]
  biome_id int [ref: > biome.id]

  indexes {
    (creature_id, biome_id) [pk]
  }
}

Table creature_2_tags {
  creature_id int [ref: > creature.id]
  raw_tag_id int [ref: > raw_tag.id]

  indexes {
    (creature_id, raw_tag_id) [pk]
  }
}

Table creature_2_caste {
  creature_id int [ref: > creature.id]
  caste_id int [ref: > caste.id]

  indexes {
    (creature_id, caste_id) [pk]
  }
}

Table caste {
  id int [pk, increment]
  description text
  baby_name int [ref: > name_data.id]
  caste_name int [ref: > name_data.id]
  child_name int [ref: > name_data.id]
  clutch_size int [ref: > min_max_data.id]
  litter_size int [ref: > min_max_data.id]
  max_age int [ref: > min_max_data.id]
  baby int
  child int
  difficult int
  egg_size int
  grass_trample int
  grazer int
  low_light_vision int
  pet_value int
  pop_ratio int
  change_body_size_percentage int
  body_size int [ref: > body_size.id]
  milkable int [ref: > milkable.id]
  tile int [ref: > tile.id]
}

Table tile {
  id int [pk, increment]
  character text
  alt_character text
  color int [ref: > color.id]
  glow_character text
  glow_color int [ref: > color.id]
}

Table milkable {
  id int [pk, increment]
  material int [ref: > material_data.id]
  frequency int

  indexes {
    (material, frequency)
    (id, material, frequency)
  }
}

Table body_size {
  id int [pk, increment]
  size_cm3 int
  years int
  days int
}

Table gait_type {
  id int [pk, increment]
  identifier text
}

Table gait {
  id int [pk, increment]
  gait_type int [ref: > gait_type.id]
  identifier text
  max_speed int
  energy_use int
}

Table caste_2_gait {
  caste_id int [ref: > caste.id]
  gait_id int [ref: > gait.id]

  indexes {
    (caste_id, gait_id) [pk]
  }
}

Table creature_class {
  id int [pk, increment]
  identifier text
  description text
}

Table caste_2_creature_class {
  caste_id int [ref: > caste.id]
  creature_class_id int [ref: > creature_class.id]

  indexes {
    (caste_id, creature_class_id) [pk]
  }
}

Table caste_2_tags {
  caste_id int [ref: > caste.id]
  raw_tag_id int [ref: > raw_tag.id]

  indexes {
    (caste_id, raw_tag_id) [pk]
  }
}

Table raw_tag_type {
  id int [pk, increment]
  name text [not null, note: The type of raw tag, e.g. CASTE or CREATURE etc.]
  description text [note: A description of the tag type.]
}

Table raw_tag {
  id int [pk, increment]
  identifier text [not null]
  name text
  description text
  has_value bit [not null, default: 0]
  has_complex_value bit [not null, default: 0]
  raw_tag_type_id int [not null, ref: > raw_tag_type.id]

  indexes {
    (identifier, raw_tag_type_id) [unique]
  }
}

Table tag_2_value {
  id int [pk, increment]
  raw_tag_id int [ref: > raw_tag.id]
  value text [note: 'The value of the tag. For complex values, store an object as a JSON string.']
  raw_value text [note: 'The literal value following the tag in the raw file.']
  indexes {
    (raw_tag_id, value) [pk]
  }
}

Table raw_tag_complex_value {
  id integer [pk, increment]
  raw_tag_id integer [not null, ref: > raw_tag.id]
  identifier text [not null]
  name text [not null]
  description text

  indexes {
    raw_tag_id
    identifier
  }
}

Table complex_tag_2_value {
  id int [pk, increment]
  complex_tag_id int [not null, ref: > raw_tag_complex_value.id]
  value text [not null]

  indexes {
    complex_tag_id
    (complex_tag_id, value)
  }
}

Table min_max_data {
  id int [pk, increment]
  minimum int [not null]
  maximum int [not null]
}

Table name_data {
  id int [pk, increment]
  singular text
  plural text
  adjective text
}

Table material_data {
  id int [pk, increment]
  identifier text
  state int [ref: > state_of_matter.id]
}

Table state_of_matter {
  id int [pk, increment]
  state text
}

Table color {
  id int [pk, increment]
  identifier text
  foreground int
  background int
  brightness int
}

Table temperature_data {
  id int [pk, increment]
  specific_heat int
  ignition_point int
  melting_point int
  boiling_point int
  heat_damage_point int
  cold_damage_point int
  material_fixed_temperature int
}

Table color_modification {
  id int [pk, increment]
  modification text [note: "AS_IS is the only one?"]
}

Table creature_effect {
  id int [pk, increment]
  severity int
  probability int
  start int
  peak int
  end int
  dwf_stretch int
}

Table creature_effect_2_body_part_category {
  creature_effect_id int [ref: > creature_effect.id]
  body_part_category text
}

Table creature_effect_2_body_part_type {
  creature_effect_id int [ref: > creature_effect.id]
  body_part_type text
}

Table creature_effect_2_body_part_token {
  creature_effect_id int [ref: > creature_effect.id]
  body_part_token text
}
Table creature_effect_2_tags {
  creature_effect_id int [ref: > creature_effect.id]
  raw_tag_id int [ref: > raw_tag.id]

  indexes {
    (creature_effect_id, raw_tag_id) [pk]
  }
}

Table dimension_data {
  x int
  y int

  indexes {
    (x, y) [pk]
  }
}