-- Populate object_type table with values from ObjectType enum
INSERT INTO object_type (identifier, description)
VALUES ('CREATURE', 'Creature'),
       ('INORGANIC', 'Inorganic'),
       ('PLANT', 'Plant'),
       ('ITEM', 'Item'),
       ('ITEM_AMMO', 'Ammo (Item)'),
       ('ITEM_ARMOR', 'Armor (Item)'),
       ('ITEM_FOOD', 'Food (Item)'),
       ('ITEM_GLOVES', 'Gloves (Item)'),
       ('ITEM_HELM', 'Helm (Item)'),
       ('ITEM_INSTRUMENT', 'Instrument (Item)'),
       ('ITEM_PANTS', 'Pants (Item)'),
       ('ITEM_SHIELD', 'Shield (Item)'),
       ('ITEM_SHOES', 'Shoes (Item)'),
       ('ITEM_SIEGEAMMO', 'Siege Ammo (Item)'),
       ('ITEM_TOOL', 'Tool (Item)'),
       ('ITEM_TOY', 'Toy (Item)'),
       ('ITEM_TRAPCOMP', 'Trap Component (Item)'),
       ('ITEM_WEAPON', 'Weapon (Item)'),
       ('BUILDING', 'Building'),
       ('BUILDING_WORKSHOP', 'Workshop Building'),
       ('BUILDING_FURNACE', 'Furnace Building'),
       ('REACTION', 'Reaction'),
       ('GRAPHICS', 'Graphics'),
       ('MATERIAL_TEMPLATE', 'Material Template'),
       ('BODY_DETAIL_PLAN', 'Body Detail Plan'),
       ('BODY', 'Body'),
       ('ENTITY', 'Entity'),
       ('LANGUAGE', 'Language'),
       ('TRANSLATION', 'Translation'),
       ('TISSUE_TEMPLATE', 'Tissue Template'),
       ('CREATURE_VARIATION', 'Creature Variation'),
       ('TEXT_SET', 'Text Set'),
       ('TILE_PAGE', 'Tile Page'),
       ('DESCRIPTOR_COLOR', 'Color Descriptor'),
       ('DESCRIPTOR_PATTERN', 'Pattern Descriptor'),
       ('DESCRIPTOR_SHAPE', 'Shape Descriptor'),
       ('PALETTE', 'Palette'),
       ('MUSIC', 'Music'),
       ('SOUND', 'Sound'),
       ('INTERACTION', 'Interaction'),
       ('UNKNOWN', 'Unknown'),
       ('SELECT_CREATURE', 'Select Creature'),
       ('CREATURE_CASTE', 'Creature Caste');