//! String token to parsed tag map for condition tokens.

use crate::tags::ConditionTag;

/// Map of condition tags to their string representation.
pub static CONDITION_TOKENS: phf::Map<&'static str, ConditionTag> = phf::phf_map! {
  "DEFAULT" => ConditionTag::Default,
  "ANIMATED" => ConditionTag::Animated,
  "CORPSE" => ConditionTag::Corpse,
  "CHILD" => ConditionTag::Child,
  "BABY" => ConditionTag::Baby,
  "TRAINED_WAR" => ConditionTag::TrainedWar,
  "TRAINED_HUNTER" => ConditionTag::TrainedHunter,
  "LIST_ICON" => ConditionTag::ListIcon,
  "SKELETON" => ConditionTag::Skeleton,
  "SKELETON_WITH_SKULL" => ConditionTag::SkeletonWithSkull,
  "ZOMBIE" => ConditionTag::Zombie,
  "NECROMANCER" => ConditionTag::Necromancer,
  "MALE" => ConditionTag::Male,
  "FEMALE" => ConditionTag::Female,
  "VAMPCURSE" => ConditionTag::VampireCursed,
  "GHOUL" => ConditionTag::Ghoul,
  "GHOST" => ConditionTag::Ghost,
  "DISTURBED_DEAD" => ConditionTag::DisturbedDead,
  "REMAINS" => ConditionTag::Remains,
  "VERMIN" => ConditionTag::Vermin,
  "LIGHT_VERMIN" => ConditionTag::LightVermin,
  "HIVE" => ConditionTag::Hive,
  "SWARM_SMALL" => ConditionTag::SwarmSmall,
  "SWARM_MEDIUM" => ConditionTag::SwarmMedium,
  "SWARM_LARGE" => ConditionTag::SwarmLarge,

  "NOT_ARTIFACT" => ConditionTag::NotArtifact,
  "IS_CRAFTED_ARTIFACT" => ConditionTag::CraftedArtifact,

  "SHRUB" => ConditionTag::Shrub,
  "PICKED" => ConditionTag::Picked,
  "SEED" => ConditionTag::Seed,
  "CROP" => ConditionTag::Crop,
  "CROP_SPROUT" => ConditionTag::CropSprout,
  "CROP_L" => ConditionTag::CropL,
  "CROP_M" => ConditionTag::CropM,
  "CROP_R" => ConditionTag::CropR,
  "SHRUB_DEAD" => ConditionTag::ShrubDead,
  "SAPLING" => ConditionTag::Sapling,

  "CONDITION_NOT_CHILD" => ConditionTag::NotChild,
  "CONDITION_CLASS" => ConditionTag::Class,
  "CONDITION_CHILD" => ConditionTag::Child,
  "CONDITION_BABY" => ConditionTag::Baby,
  "CONDITION_HAUL_COUNT_MIN" => ConditionTag::HaulCountMin,
  "CONDITION_HAUL_COUNT_MAX" => ConditionTag::HaulCountMax,
  "CONDITION_ITEM_WORN" => ConditionTag::ItemWorn,
  "CONDITION_PROFESSION_CATEGORY" => ConditionTag::ProfessionCategory,
  "CONDITION_SYN_CLASS" => ConditionTag::SyndromeClass,
  "CONDITION_CASTE" => ConditionTag::Caste,
  "CONDITION_TISSUE_LAYER" => ConditionTag::TissueLayer,
  "CONDITION_MATERIAL_FLAG" => ConditionTag::MaterialFlag,
  "CONDITION_MATERIAL_TYPE" => ConditionTag::MaterialType,
  "CONDITION_DYE" => ConditionTag::Dye,
  "CONDITION_DYED" => ConditionTag::Dye,
  "CONDITION_NOT_DYED" => ConditionTag::NotDyed,
  "SHUT_OFF_IF_ITEM_PRESENT" => ConditionTag::ShutOffIfItemPresent,
  "CONDITION_RANDOM_PART_INDEX" => ConditionTag::RandomPartIndex,
  "CONDITION_GHOST" => ConditionTag::Ghost,
  "TISSUE_MAY_HAVE_COLOR" => ConditionTag::TissueMayHaveColor,
  "TISSUE_MIN_LENGTH" => ConditionTag::TissueMinLength,
  "TISSUE_MAX_LENGTH" => ConditionTag::TissueMaxLength,
  "TISSUE_MAY_HAVE_SHAPING" => ConditionTag::TissueMayHaveShaping,
  "TISSUE_NOT_SHAPED" => ConditionTag::TissueNotShaped,
  "TISSUE_SWAP" => ConditionTag::TissueSwap,
  "TISSUE_MIN_CURLY" => ConditionTag::TissueMinCurly,
  "TISSUE_MAX_CURLY" => ConditionTag::TissueMaxCurly,
  // Generic condition (or something)
  "CONDITION" => ConditionTag::Condition,

  // Professions...
  "HAMMERMAN" => ConditionTag::Hammerman,
  "MASTER_HAMMERMAN" => ConditionTag::MasterHammerman,
  "SPEARMAN" => ConditionTag::Spearman,
  "MASTER_SPEARMAN" => ConditionTag::MasterSpearman,
  "WRESTLER" => ConditionTag::Wrestler,
  "MASTER_WRESTLER" => ConditionTag::MasterWrestler,
  "AXEMAN" => ConditionTag::Axeman,
  "MASTER_AXEMAN" => ConditionTag::MasterAxeman,
  "SWORDSMAN" => ConditionTag::Swordsman,
  "MASTER_SWORDSMAN" => ConditionTag::MasterSwordsman,
  "MACEMAN" => ConditionTag::Maceman,
  "MASTER_MACEMAN" => ConditionTag::MasterMaceman,
  "PIKEMAN" => ConditionTag::Pikeman,
  "MASTER_PIKEMAN" => ConditionTag::MasterPikeman,
  "RECRUIT" => ConditionTag::Recruit,
  "THIEF" => ConditionTag::Thief,
  "MASTER_THIEF" => ConditionTag::MasterThief,
  "LASHER" => ConditionTag::Lasher,
  "MASTER_LASHER" => ConditionTag::MasterLasher,
  "MONSTER_SLAYER" => ConditionTag::MonsterSlayer,
  "CROSSBOWMAN" => ConditionTag::Crossbowman,
  "MASTER_CROSSBOWMAN" => ConditionTag::MasterCrossbowman,
  "BOWMAN" => ConditionTag::Bowman,
  "MASTER_BOWMAN" => ConditionTag::MasterBowman,
  "BLOWGUNMAN" => ConditionTag::Blowgunman,
  "MASTER_BLOWGUNMAN" => ConditionTag::MasterBlowgunman,
  "BEAST_HUNTER" => ConditionTag::BeastHunter,
  "SCOUT" => ConditionTag::Scout,
  "RANGER" => ConditionTag::Ranger,
  "HUNTER" => ConditionTag::Hunter,
  "SAGE" => ConditionTag::Sage,
  "SCHOLAR" => ConditionTag::Scholar,
  "PHILOSOPHER" => ConditionTag::Philosopher,
  "MATHEMATICIAN" => ConditionTag::Mathematician,
  "HISTORIAN" => ConditionTag::Historian,
  "ASTRONOMER" => ConditionTag::Astronomer,
  "NATURALIST" => ConditionTag::Naturalist,
  "CHEMIST" => ConditionTag::Chemist,
  "GEOGRAPHER" => ConditionTag::Geographer,
  "SCRIBE" => ConditionTag::Scribe,
  "BOOKBINDER" => ConditionTag::Bookbinder,
  "PERFORMER" => ConditionTag::Performer,
  "POET" => ConditionTag::Poet,
  "BARD" => ConditionTag::Bard,
  "DANCER" => ConditionTag::Dancer,

  "LS_PALETTE" => ConditionTag::LayerSetPalette,
  "LS_PALETTE_FILE" => ConditionTag::LayerSetPaletteFile,
  "LS_PALETTE_DEFAULT" => ConditionTag::LayerSetPaletteDefault,
  "VERMIN_ALT" => ConditionTag::VerminAlt,
  "LIGHT_VERMIN_ALT" => ConditionTag::LightVerminAlt,
  "LIGHT_SWARM_SMALL" => ConditionTag::LightSwarmSmall,
  "LIGHT_SWARM_MEDIUM" => ConditionTag::LightSwarmMedium,
  "LIGHT_SWARM_LARGE" => ConditionTag::LightSwarmLarge,
  "ITEM_QUALITY" => ConditionTag::ItemQuality,
  "USE_PALETTE" => ConditionTag::UsePalette,
  "USE_STANDARD_PALETTE_FROM_ITEM" => ConditionTag::UseStandardPaletteFromItem,
};
