//! String token to parsed tag map for creature tokens.

use crate::{custom_types::TileCharacter, tags::CreatureTag};

/// A map of creature tags to their respective enum values.
pub static CREATURE_TOKENS: phf::Map<&'static str, CreatureTag> = phf::phf_map! {
    "ARTIFICIAL_HIVEABLE" => CreatureTag::ArtificialHiveable,
    "DOES_NOT_EXIST" => CreatureTag::DoesNotExist,
    "EVIL" => CreatureTag::Evil,
    "GOOD" => CreatureTag::Good,
    "FANCIFUL" => CreatureTag::Fanciful,
    "SAVAGE" => CreatureTag::Savage,
    "GENERATED" => CreatureTag::Generated,
    "UBIQUITOUS" => CreatureTag::Ubiquitous,
    "VERMIN_FISH" => CreatureTag::VerminFish,
    "VERMIN_SOIL" => CreatureTag::VerminSoil,
    "VERMIN_SOIL_COLONY" => CreatureTag::VerminSoilColony,
    "VERMIN_ROTTER" => CreatureTag::VerminRotter,
    "VERMIN_GROUNDER" => CreatureTag::VerminGrounder,
    "VERMIN_EATER" => CreatureTag::VerminEater,
    "FREQUENCY" => CreatureTag::Frequency { frequency: 0 },
    "UNDERGROUND_DEPTH" => CreatureTag::UndergroundDepth { min: 0, max: 0 },
    "LARGE_ROAMING" => CreatureTag::LargeRoaming,
    "LOCAL_POPS_CONTROLLABLE" => CreatureTag::LocalPopsControllable,
    "LOCAL_POPS_PRODUCE_HEROES" => CreatureTag::LocalPopsProduceHeroes,
    "LOOSE_CLUSTERS" => CreatureTag::LooseClusters,
    "MUNDANE" => CreatureTag::Mundane,
    "BIOME" => CreatureTag::Biome { id: String::new() },
    "PREFSTRING" => CreatureTag::PrefString { pref_string: String::new() },
    "NAME" => CreatureTag::Name { name: String::new(), plural_name: String::new(), adjective: String::new() },
    "GENERAL_BABY_NAME" => CreatureTag::GeneralBabyName { singular: String::new(), plural: String::new() },
    "GENERAL_CHILD_NAME" => CreatureTag::GeneralChildName { singular: String::new(), plural: String::new() },
    "POPULATION_NUMBER" => CreatureTag::PopulationNumber { min: 0, max: 0 },
    "COPY_TAGS_FROM" => CreatureTag::CopyTagsFrom { creature: String::new() },
    "CREATURE_TILE" => CreatureTag::CreatureTile { character: TileCharacter::new() },
    "ALTTILE" => CreatureTag::AltTile { character: TileCharacter::new() },
    "COLOR" => CreatureTag::Color { foreground: 0, background: 0, brightness: 0 },
    "GLOWCOLOR" => CreatureTag::GlowColor { foreground: 0, background: 0, brightness: 0 },
    "GLOWTILE" => CreatureTag::GlowTile { character: TileCharacter::new()  },
    "CHANGE_FREQUENCY_PERC" => CreatureTag::ChangeFrequencyPercent { percent: 0 },
    "CLUSTER_NUMBER" => CreatureTag::ClusterNumber { min: 0, max: 0 },
    "MATES_TO_BREED" => CreatureTag::MatesToBreed,
    "ALL_CASTES_ALIVE" => CreatureTag::AllCastesAlive,
    "TWO_GENDERS" => CreatureTag::TwoGenders,
    "SMALL_RACE" => CreatureTag::SmallRace,
    "OCCURS_AS_ENTITY_RACE" => CreatureTag::OccursAsEntityRace,
    "EQUIPMENT" => CreatureTag::Equipment,
    "EQUIPMENT_WAGON" => CreatureTag::EquipmentWagon,
};
