//! String token to parsed tag map for position tokens.

use crate::tokens::PositionToken;

/// Mapping of position tokens to strings
pub static POSITION_TOKENS: phf::Map<&'static str, PositionToken> = phf::phf_map! {
  "ACCOUNT_EXEMPT" => PositionToken::AccountExempt,
  "ALLOWED_CLASS" => PositionToken::AllowedClass {class: String::new()},
  "ALLOWED_CREATURE" => PositionToken::AllowedCreature {caste: String::new(),creature: String::new()},
  "APPOINTED_BY" => PositionToken::AppointedBy{position: String::new()},
  "BRAG_ON_KILL" => PositionToken::BragOnKill,
  "CHAT_WORTHY" => PositionToken::ChatWorthy,
  "COLOR" => PositionToken::Color{background:0,brightness:0,foreground:0},
  "COMMANDER" => PositionToken::Commander{commanded_position: String::new(),position: String::new()},
  "CONQUERED_SITE" => PositionToken::ConqueredSite,
  "DEMAND_MAX" => PositionToken::DemandMax{amount:0},
  "DETERMINES_COIN_DESIGN" => PositionToken::DeterminesCoinDesign,
  "DO_NOT_CULL" => PositionToken::DoNotCull,
  "DUTY_BOUND" => PositionToken::DutyBound,
  "ELECTED" => PositionToken::Elected,
  "EXECUTION_SKILL" => PositionToken::ExecutionSkill{skill: String::new()},
  "EXPORTED_IN_LEGENDS" => PositionToken::ExportedInLegends,
  "FLASHES" => PositionToken::Flashes,
  "GENDER" => PositionToken::Gender{name: String::new()},
  "KILL_QUEST" => PositionToken::KillQuest,
  "LAND_HOLDER" => PositionToken::LandHolder{importance:0},
  "LAND_NAME" => PositionToken::LandName { name: String::new() },
  "MANDATE_MAX" => PositionToken::MandateMax,
  "MENIAL_WORK_EXEMPTION" => PositionToken::MenialWorkExemption,
  "MENIAL_WORK_EXEMPTION_SPOUSE" => PositionToken::MenialWorkExemptionSpouse,
  "MILITARY_SCREEN_ONLY" => PositionToken::MilitaryScreenOnly,
  "NAME" => PositionToken::Name { singular: String::new(), plural: String::new() },
  "NAME_MALE" => PositionToken::NameMale { singular: String::new(), plural: String::new() },
  "NAME_FEMALE" => PositionToken::NameFemale { singular: String::new(), plural: String::new() },
  "DESCRIPTION" => PositionToken::Description { description: String::new() },
  "NUMBER" => PositionToken::Number { number: crate::custom_types::Amount::None },
  "PRECEDENCE" => PositionToken::Precedence { importance: crate::custom_types::Amount::None },
  "PUNISHMENT_EXEMPTION" => PositionToken::PunishmentExemption,
  "QUEST_GIVER" => PositionToken::QuestGiver,
  "REJECTED_CLASS" => PositionToken::RejectedClass { class: String::new() },
  "REJECTED_CREATURE" => PositionToken::RejectedCreature { creature: String::new(), caste: String::new() },
  "REPLACED_BY" => PositionToken::ReplacedBy { position: String::new() },
  "REQUIRED_BEDROOM" => PositionToken::RequiredBedroom { value: 0 },
  "REQUIRED_BOXES" => PositionToken::RequiredBoxes { amount: 0 },
  "REQUIRED_CABINETS" => PositionToken::RequiredCabinets { amount: 0 },
  "REQUIRED_DINING" => PositionToken::RequiredDining { value: 0 },
  "REQUIRED_OFFICE" => PositionToken::RequiredOffice { value: 0 },
  "REQUIRED_RACKS" => PositionToken::RequiredRacks { amount: 0 },
  "REQUIRED_STANDS" => PositionToken::RequiredStands { amount: 0 },
  "REQUIRED_TOMB" => PositionToken::RequiredTomb { value: 0 },
  "REQUIRES_MARKET" => PositionToken::RequiresMarket,
  "REQUIRES_POPULATION" => PositionToken::RequiresPopulation { population: 0 },
  "RESPONSIBILITY" => PositionToken::Responsibility { responsibility: String::new() },
  "RULES_FROM_LOCATION" => PositionToken::RulesFromLocation,
  "SITE" => PositionToken::Site,
  "SLEEP_PRETENSION" => PositionToken::SleepPretension,
  "SPECIAL_BURIAL" => PositionToken::SpecialBurial,
  "SPOUSE" => PositionToken::Spouse { singular: String::new(), plural: String::new() },
  "SPOUSE_FEMALE" => PositionToken::SpouseFemale { singular: String::new(), plural: String::new() },
  "SPOUSE_MALE" => PositionToken::SpouseMale { singular: String::new(), plural: String::new() },
  "SQUAD" => PositionToken::Squad { headcount: 0, singular: String::new(), plural: String::new() },
  "SUCCESSION" => PositionToken::Succession { inheritor: String::new() },
};
