//! String token to parsed tag map for position tokens.

use crate::tokens::PositionToken;

/// Mapping of position tokens to strings
pub static POSITION_TOKENS: phf::Map<&'static str, PositionToken> = phf::phf_map! {
  "ACCOUNT_EXEMPT" => PositionToken::AccountExempt,
  "ALLOWED_CLASS" => PositionToken::AllowedClass,
  "ALLOWED_CREATURE" => PositionToken::AllowedCreature,
  "APPOINTED_BY" => PositionToken::AppointedBy,
  "BRAG_ON_KILL" => PositionToken::BragOnKill,
  "CHAT_WORTHY" => PositionToken::ChatWorthy,
  "COLOR" => PositionToken::Color,
  "COMMANDER" => PositionToken::Commander,
  "CONQUERED_SITE" => PositionToken::ConqueredSite,
  "DEMAND_MAX" => PositionToken::DemandMax,
  "DETERMINES_COIN_DESIGN" => PositionToken::DeterminesCoinDesign,
  "DO_NOT_CULL" => PositionToken::DoNotCull,
  "DUTY_BOUND" => PositionToken::DutyBound,
  "ELECTED" => PositionToken::Elected,
  "EXECUTION_SKILL" => PositionToken::ExecutionSkill,
  "EXPORTED_IN_LEGENDS" => PositionToken::ExportedInLegends,
  "FLASHES" => PositionToken::Flashes,
  "GENDER" => PositionToken::Gender,
  "KILL_QUEST" => PositionToken::KillQuest,
  "LAND_HOLDER" => PositionToken::LandHolder,
  "LAND_NAME" => PositionToken::LandName,
  "MANDATE_MAX" => PositionToken::MandateMax,
  "MENIAL_WORK_EXEMPTION" => PositionToken::MenialWorkExemption,
  "MENIAL_WORK_EXEMPTION_SPOUSE" => PositionToken::MenialWorkExemptionSpouse,
  "MILITARY_SCREEN_ONLY" => PositionToken::MilitaryScreenOnly,
  "NAME" => PositionToken::Name,
  "NAME_MALE" => PositionToken::NameMale,
  "NAME_FEMALE" => PositionToken::NameFemale,
  "DESCRIPTION" => PositionToken::Description,
  "NUMBER" => PositionToken::Number,
  "PRECEDENCE" => PositionToken::Precedence,
  "PUNISHMENT_EXEMPTION" => PositionToken::PunishmentExemption,
  "QUEST_GIVER" => PositionToken::QuestGiver,
  "REJECTED_CLASS" => PositionToken::RejectedClass,
  "REJECTED_CREATURE" => PositionToken::RejectedCreature,
  "REPLACED_BY" => PositionToken::ReplacedBy,
  "REQUIRED_BEDROOM" => PositionToken::RequiredBedroom,
  "REQUIRED_BOXES" => PositionToken::RequiredBoxes,
  "REQUIRED_CABINETS" => PositionToken::RequiredCabinets,
  "REQUIRED_DINING" => PositionToken::RequiredDining,
  "REQUIRED_OFFICE" => PositionToken::RequiredOffice,
  "REQUIRED_RACKS" => PositionToken::RequiredRacks,
  "REQUIRED_STANDS" => PositionToken::RequiredStands,
  "REQUIRED_TOMB" => PositionToken::RequiredTomb,
  "REQUIRES_MARKET" => PositionToken::RequiresMarket,
  "REQUIRES_POPULATION" => PositionToken::RequiresPopulation,
  "RESPONSIBILITY" => PositionToken::Responsibility,
  "RULES_FROM_LOCATION" => PositionToken::RulesFromLocation,
  "SITE" => PositionToken::Site,
  "SLEEP_PRETENSION" => PositionToken::SleepPretension,
  "SPECIAL_BURIAL" => PositionToken::SpecialBurial,
  "SPOUSE" => PositionToken::Spouse,
  "SPOUSE_FEMALE" => PositionToken::SpouseFemale,
  "SPOUSE_MALE" => PositionToken::SpouseMale,
  "SQUAD" => PositionToken::Squad,
  "SUCCESSION" => PositionToken::Succession,
};
