use crate::tokens::MaterialStateToken;

pub enum TissueToken {
    Name {name: Name},
    Material { material_token: String,},
    RelativeThickness {thickness: u32},
    HealingRate {rate: u32},
    Vascular {bleeding_rate: u32},
    PainReceptors {sensitivity: u32},
    ThickensOnStrength,
    ThickensOnEnergyStorage,
    Arteries,
    Scars,
    Structural,
    ConnectiveTissueAnchor,
    Settable,
    Splintable,
    Functional,
    Nervous,
    Thought,
    Muscular,
    Smell,
    Hear,
    Flight,
    Breathe,
    Sight,
    Connects,
    MajorArteries,
    Insulation {value: u32},
    Cosmetic,
    Styleable,
    Shape { shape: TissueShape,},
    SubordinateToTissue { tissue: String },
    TissueMaterialState { state: MaterialStateToken}
}
